version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/pgsql/data
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  jar:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/

volumes:
  pgdata:
